### ISSUE TITLE
🐛 can't find contents of sångbok.

### ISSUE THREAD

**Issue by MajaScherman** [Dsek-LTH/member-page#1076]
So you encountered a bug?  😝 🐛 We really appreciate your help! 🥇 
## Short description of the bug
Can't find the songs of sångbok. The search function seems broken.

I'd love to see a view with all the songs we have. 

## Context
Screenshots or other data that is relevant to the bug.

## Environment (If applicable)
 - Device(e.g. iPhone, desktop):
 - OS: (e.g. iOS):
 - Browser (e.g. chrome, safari):
 - Version (e.g. 22):

**Comment by Macludde** [comment]
Hi Maja! Currently we have not migrated over the songs from the old website, partially due to some of them being problematic (to say the least) and we haven't decided on how to fix this.

I'll make sure to bump this issue when songs have been migrated over and the data has been added.
