### ISSUE TITLE
✨ Add "Stabsmode" to the profile pages of active members of the "Stab"

### ISSUE THREAD

**Issue by Macludde** [Dsek-LTH/member-page#1118]
## Short description of the feature
The "Stab" ususally wants to stay anonymous during the introductory period, but it would still be fun for them to be displayed on the website. It would therefore be cool if the stab member's profiles displayed their alter egos (other names and profile pictures). Apart from this, the emails should be hidden and ALL other mandates except "stab" or "øverphøs" should be hidden. It would be cool if the profile page also had some cool effects.

## Technical implementation
Since there are only 6 people on the entire guild to which this applies, I don't think this should be done in the database. Instead, a simple backend (or frontend) filter should suffice. It could then check if the user has a current mandate of either "stabsmedlem" or "øverphøs" and the current time period is between august and october (or more exact dates, these could either be hard coded or edited somewhere. When developing the introduction period website I'm guessing this is going to be configured somewhere on the site anyways.). If these conditions are met, the profile page should be customized according to above.

The user's has to self be in charge of updating their names and profile pictures.

**Comment by Macludde** [comment]
<img width="660" alt="image" src="https://github.com/Dsek-LTH/member-page/assets/29541261/36826e1e-b3de-4fc5-9a45-4e62ad6745d2">

To clarify, the following should be hidden:
- StiL-id
- Year and programme
- E-mail
- All other mandates
- Year for mandate


It should therefore look like:

**Zira Callisto**
*Överphös*

**Comment by danieladugyan** [comment]
We could replace member_id on the backend with null like we did on accident :)
