### ISSUE TITLE
🐛 Policies and guidelines are missing

### ISSUE THREAD

**Issue by fnurkla** [Dsek-LTH/member-page#1143]
This is democratic issue :angry: ![image](https://github.com/Dsek-LTH/member-page/assets/97372888/9c06a5bb-de61-4c1a-a8d3-d1cd8018e524)

**Comment by valterbergstrand** [comment]
I want to ping this issue :) If I am not misunderstanding something, the only way of accessing the policies and guidelines right now is through having to download/clone the github repo and then building the pdfs yourselfs locally. Even though the policies and guidelines aren't checked often, it could cause problems if you downloaded an old version of a policy and in turn are following a outdated version.
