### ISSUE TITLE
🐛 Events can only have one tag

### ISSUE THREAD

**Issue by Macludde** [Dsek-LTH/member-page#1214]
![image](https://github.com/Dsek-LTH/member-page/assets/29541261/c35c996e-bcd7-4453-8fb3-f46a6f1da4a2)
The issue is right here. Should be `t.unique(['event_id','tag_id'])`

Will need a new migration.

**Comment by danieladugyan** [comment]
That's annoying, good find. I guess I'll fix it in when we ship our nolla event calendar.
