### ISSUE TITLE
Add MySQL docker for production env

### ISSUE THREAD

**Issue by emilwihlander** [Dsek-LTH/member-page#15]

**Comment by hnrklssn** [comment]
Är det sunt att köra MySQL i prod och SQLite i dev? Skiljer inte de sig i beteende och funktionalitet?

**Comment by emilwihlander** [comment]
Det stämmer att det finns mindre skillnader men det var mycket lättare att sätta upp sqlite lokalt så därför valde jag inte mySQL initialt. Jag tänker att när docker är uppsatt kan även dev gå över till mySQL eftersom det kommer vara enkelt att sätta upp då.

**Comment by hnrklssn** [comment]
Docker är uppsatt, inkl MySQL. Se t.ex https://github.com/Dsek-LTH/gateway/blob/master/docker-compose.yml och https://github.com/Dsek-LTH/gateway/blob/master/Dockerfile. Det går att migrera till ett monorepo utan att kasta allt tidigare arbete (igen). Gör vi det varje år kommer vi aldrig någonstans. Är det något du undrar över är det bara att fråga!

**Comment by emilwihlander** [comment]
Gjorde en liknande set-up för bordsbeställningssystemet som användes under nollningen så tänkte fixa det imorgon förmiddag men kommer absolut ta inspiration från den filen! I och med monorepo blir compose-filen antagligen aningen mindre komplicerad.

**Comment by hnrklssn** [comment]
Monorepo lär inte påverka nämnvärt eftersom varje tjänst fortfarande kommer köra i en separat container. Monorepo gör det bara enklare att göra PRs som påverkar flera tjänster samtidigt, och dela kod mellan tjänster.
