### ISSUE TITLE
✨ Send notification on status change for a booking request

### ISSUE THREAD

**Issue by noahmay** [Dsek-LTH/member-page#158]
## Short description of the feature
When a  booking requests changes status from pending to approved for example an email should be sent to the booker. 

[ ] Relates to frontend
[x] Relates to the backend
[ ] Requires modification of GraphQL
[ ] Requires modification of Database
[ ] Requires creating a new service

**Comment by noahmay** [comment]
Waiting for new mail from root

**Comment by oliverlevay** [comment]
Since the mail server is taking so long we have no choice but to implement a notifications system ourselves.
