### ISSUE TITLE
Switch from MYSQL DB to PostgresSQL

### ISSUE THREAD

**Issue by noahmay** [Dsek-LTH/member-page#188]
Postgress has custom types that would solve some problems on the backend. And some other features that might be nice to have in the feature for example UUID as a type and better real-time support.

[ ] Relates to frontend
[x] Relates to the backend
[ ] Requires modification of GraphQL
[x] Requires modification of Database
[ ] Requires creating a new service

**Comment by hnrklssn** [comment]
Om ni har specifika anledningar för designbeslut kan det vara en bra idé att skriva dem i ticketen så att efterlevande kan referera tillbaka till varför ändringarna gjordes. Annars står man där i framtiden och vill ändra något, men är osäker på om man har missat anledningen till varför det gjordes på just detta viset. Eller så gör man en stor omfaktorisering och inser inte förrän efteråt att det inte funkar på det viset. Finns det ingen info i ticketen ger det inget mervärde att länka tillbaka dem i commitmeddelandet.

**Comment by noahmay** [comment]
Du har helt rätt. La in issuen för jag inte skulle missa att göra det men ska tänka på det i framtiden.
