### ISSUE TITLE
[build] Evaluate if docker compose can replace docker-compose

### ISSUE THREAD

**Issue by emilwihlander** [Dsek-LTH/member-page#189]
## Short description of the feature
I got det message `Docker Compose is now in the Docker CLI, try "docker compose up"` when running the development command. I then found this article (https://docs.docker.com/compose/cli-command/) and it seems as though `docker compose` is the future but it is recommended to evaluate whether it works for each specific project.

**Comment by LucasBoberg** [comment]
Det fungerar exakt lika bra

**Comment by noahmay** [comment]
Can this be closed?

**Comment by emilwihlander** [comment]
This can be closed when README is updated to use docker compose instead of docker-compose
