### ISSUE TITLE
Add tests to backend and run for every pull request

### ISSUE THREAD

**Issue by emilwihlander** [Dsek-LTH/member-page#19]

**Comment by hnrklssn** [comment]
Vilken typ av tester har du tänkt dig? Sanity checks, integreringstester, enhetstester..?

**Comment by emilwihlander** [comment]
Initialt tänker jag enhetstester + intregrationstester på service nivå. Har kollat lite på detta och har kommit fram till att en lösning med mocha + knex-mock + apollo-server-testing borde vara den bästa approachen. Kommer mig nog sätta mig med detta idag.
