### ISSUE TITLE
[Feature] Implement form validation

### ISSUE THREAD

**Issue by LucasBoberg** [Dsek-LTH/member-page#221]
## Short description of the feature
Form validation needs to be implemented on almost all of the input forms to make sure the user cannot create broken requests

[x] Relates to frontend
[ ] Relates to the backend
[ ] Requires modification of GraphQL
[ ] Requires modification of Database
[ ] Requires creating a new service

**Comment by oliverlevay** [comment]
This issue is too broad. Input validation where?
