### ISSUE TITLE
Uppdatera formatet på commit-meddelanden

### ISSUE THREAD

**Issue by hnrklssn** [Dsek-LTH/member-page#24]
För att dra full nytta av GHs issuetracker skulle det vara najs med commitmeddelanden som triggar den automatiska länkningen mellan PR och issue. Detta gör dels att det enkelt går att se att det finns en PR igång om man kollar på en issue, ger bättre överblick på [projektsidan](https://github.com/orgs/Dsek-LTH/projects/4), och gör att issuen automatiskt stängs när PRn mergats.

https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

**Comment by hnrklssn** [comment]
Skapade detta projektet nu: https://github.com/Dsek-LTH/member-page/projects/1
Vet inte om det är bättre eller inte, men tänkte att det kanske kan finnas tajtare integrering för projekt direkt på repot än för organisationen. Men ja, kan vara värt att läsa på om. Eller inte. :shrug:

**Comment by emilwihlander** [comment]
Personligen har jag under tiden jag arbetat i år inte känt att projekt ger speciellt mycket extra, så länge man underhåller sina issues löser det allt, imo. Däremot gillar jag att att det går att automatiskt länka issues! Kan vara värt att se över hur commitmeddelanden ska se ut och hur vi hanterar labels som nämns i #25, kanske värt att inte ha någon standard på commit-meddelanden men på pull requests?
