### ISSUE TITLE
[Booking] Make it possible to approve a booking with access

### ISSUE THREAD

**Issue by noahmay** [Dsek-LTH/member-page#247]
## Short description of the feature
When approving a booking make it possible to also give the booker access to the rooms required for the booking to work. 

 Write Depends on #246

[x] Relates to frontend
[ ] Relates to the backend
[x] Requires modification of GraphQL
[ ] Requires modification of Database
[ ] Requires creating a new service

## Long description with technical specifications

To make sure the booker has access to the booked room give access to all places needed to access that room (For example, if "Styreserummet" is booked give access to "iDét" and "Styreserummet"). This can be done by creating a time-limited access policy for the duration of the event +- 2 hours (or something) to make sure they have access when the event starts and some time for cleanup.

**Comment by oliverlevay** [comment]
For this to be implemented we need to have some sort of connection between doors and bookables
