### ISSUE TITLE
Uppdatera issue labels

### ISSUE THREAD

**Issue by hnrklssn** [Dsek-LTH/member-page#25]
Beroende på hur #24 går så kan det vara värt att uppdatera vilka labels man kan markera issues med så att de reflekterar taggarna i commitmeddelanden. På så sätt finns det ingen otydlighet kring vilken tagg man ska använda när man skapar en PR.
Givet att vi fortsätter med taggar i commitmeddelanden, alltså. Ser personligen inte grejen med det. Imo är det viktigare att se den i issuen, som dessutom är länkad till genom commitmeddelandet.

**Comment by emilwihlander** [comment]
Rimligtvis kan vi använda commit-taggarna som grund plus några till

feature: new functionality
bugfix: fixes erroneous functionality
refactor: no functionality change but nicer looking code
config: changes to config files
build: changes to build files, process, etc.
misc: other changes, e.g. README

Plus dessa kanske?
blocked: issue blocked by another issue
good first issue: New to DWWW? Start here
discussion: Issue needs to be discussed
low priority: Issue shouldn't be prioritized

Någon mer du kan komma på?

**Comment by hnrklssn** [comment]
Det ser bra ut! Eventuellt typ documentation och code-style (som kontrast till refactor som är mer än type whitespace-ändringar) också?

**Comment by emilwihlander** [comment]
Låter bra! Kom även på att det kan vara bra att ha en frontend och en backend label

**Comment by emilwihlander** [comment]
Nu har jag lagt till dessa samt taggat alla nuvarande issues, ser det bra ut @hnrklssn ?

**Comment by hnrklssn** [comment]
Yes, jag är nöjd :)
