### ISSUE TITLE
[Pagination] Update pagination data object to not be the same name

### ISSUE THREAD

**Issue by LucasBoberg** [Dsek-LTH/member-page#261]
## Short description of the feature
Currently, you have to type for example "events.events" it would be nicer to be able to write "eventsPagination.events" or something similar.

[X] Relates to frontend
[X] Relates to the backend
[X] Requires modification of GraphQL
[ ] Requires modification of Database
[ ] Requires creating a new service

**Comment by emilwihlander** [comment]
A more common way to do this is to name the data field (the field containing the list of items) something generic, such as items/content/data (seems as the most popular option in graphQL is nodes). This would lead to an object path where you don't repeat the noun (e.g. events.nodes).

**Comment by oliverlevay** [comment]
I like events.items , so like data.events.items

**Comment by oliverlevay** [comment]
Lets think about this when we implement this in the future. We don't want to break our API.
