### ISSUE TITLE
[Frontend] Add breadcrumbs to pages

### ISSUE THREAD

**Issue by LucasBoberg** [Dsek-LTH/member-page#263]
## Short description of the feature
Breadcrumbs is a design pattern for easier navigation and would be a nice addition to some pages.

see https://mui.com/components/breadcrumbs/#main-content

[X] Relates to frontend
[ ] Relates to the backend
[ ] Requires modification of GraphQL
[ ] Requires modification of Database
[ ] Requires creating a new service

**Comment by oliverlevay** [comment]
This issue is too vague and broad to ever be worked on.
