### ISSUE TITLE
[access] Hard code that DWWW always has access to create/read/update/delete for policies

### ISSUE THREAD

**Issue by emilwihlander** [Dsek-LTH/member-page#272]
## Short description of the feature
Hard code that DWWW always has access to create/read/update/delete for policies to ensure that nobody can lock DWWW out of the system.

[ ] Relates to frontend
[X] Relates to the backend
[ ] Requires modification of GraphQL
[ ] Requires modification of Database
[ ] Requires creating a new service

**Comment by oliverlevay** [comment]
We will always be able to update the pgadmin, wontdo
