### ISSUE TITLE
[Frontend] Investigate global error snackbar/toast

### ISSUE THREAD

**Issue by LucasBoberg** [Dsek-LTH/member-page#278]
## Short description of the feature
Check to see if we can have a single maybe provider with a global state where errors can be sett to show better error messages on different pages.

[X] Relates to frontend
[ ] Relates to the backend
[ ] Requires modification of GraphQL
[ ] Requires modification of Database
[ ] Requires creating a new service

**Comment by noahmay** [comment]
This can be done using a provider. Working on a PR with a proposal
