### ISSUE TITLE
[core] Add a customizable tassel (tofs) to the user profile 

### ISSUE THREAD

**Issue by ax6160sv-s** [Dsek-LTH/member-page#298]
## Short description of the feature
Add a customizable tassel (tofs) to the user profile, like the one on the old site, but better looking (3D? 👀).

[x] Relates to frontend
[x] Relates to the backend
[x] Requires modification of GraphQL
[x] Requires modification of Database
[ ] Requires creating a new service

## Long description with technical specifications
The tassel should be a nullable member of the user class, so you can choose not to have one. 
It should basically consist of two attributes, one string which describes what spegats/other stuff you have hanging in it, and a height so you can raise it when appropriate.

Frontend wise 3D rendering would be cool, but probably takes a lot more effort. If it proves unfeasible, using SVGs should make for something that looks clean enough.

**Comment by ax6160sv-s** [comment]
Personally, this is one of my favorite features of the old site, so seeing it return would be nice.

**Comment by noahmay** [comment]
DWWW likes this idea. And would love to see a PR.

**Comment by emilwihlander** [comment]
I could help with the backend probably!

**Comment by noahmay** [comment]
@ax6160sv-s we spoke a little bit about doing it in 3D. If you want to do a 3D tassel https://threejs.org/ might be interesting

**Comment by oliverlevay** [comment]
Are one of you going to work on this? @noahmay @emilwihlander 
Otherwise I will close this issue and perhaps implement this in the future if it's a popular request when we have a good flow for feature requests.

**Comment by oliverlevay** [comment]
Will open again later

**Comment by Whizma** [comment]
This would be an awesome addition to the new member page! I will do some investigating to see if it would be possible to migrate the old solution
