### ISSUE TITLE
[news] Add a mandate field on news

### ISSUE THREAD

**Issue by oliverlevay** [Dsek-LTH/member-page#299]
## Short description of the feature
Add a mandate field on news. To be able to filter on which committee is responsible for a news article, and also show the current mandate of the author, for example "Cafémästare".

[ ] Relates to frontend
[ x ] Relates to the backend
[ x ] Requires modification of GraphQL
[ x ] Requires modification of Database
[ ] Requires creating a new service

**Comment by emilwihlander** [comment]
The way it works on the current site is that you can choose which mandate you want to publish things as. I think that is the most elegant solution, I'll try to implement something similar on the backend. This will require the frontend for article creation to include a field for choosing a mandate.

**Comment by oliverlevay** [comment]
> The way it works on the current site is that you can choose which mandate you want to publish things as. I think that is the most elegant solution, I'll try to implement something similar on the backend. This will require the frontend for article creation to include a field for choosing a mandate.

Sounds good to me! I will make a new issue for this.
