### ISSUE TITLE
[Frontend] Change small calender on home page to list of upcoming events

### ISSUE THREAD

**Issue by noahmay** [Dsek-LTH/member-page#312]
## Short description of the feature
it's hard to see what events are upcoming in the small calendar. The small calendar on the home page should be changed to a list of upcoming events instead.

[x] Relates to frontend
[ ] Relates to the backend
[ ] Requires modification of GraphQL
[ ] Requires modification of Database
[ ] Requires creating a new service

**Comment by oliverlevay** [comment]
Depends on #291

**Comment by oliverlevay** [comment]
I'm not sure that we actually want this, especially at this time since we don't have any upcoming events.
