### ISSUE TITLE
[core] Query active mandates on a Member

### ISSUE THREAD

**Issue by oliverlevay** [Dsek-LTH/member-page#313]
## Short description of the feature
To prepare for listing a members active mandates we need to add which mandates a member has

[ ] Relates to frontend
[x] Relates to the backend
[x] Requires modification of GraphQL
[ ] Requires modification of Database
[ ] Requires creating a new service

**Comment by emilwihlander** [comment]
I guess it would be nice if you could query both for active and inactive mandates for a member?
