### ISSUE TITLE
[access] Troubleshoot access roles

### ISSUE THREAD

**Issue by LucasBoberg** [Dsek-LTH/member-page#315]
## Short description of the feature
Troubleshoot both the frontend and backend to make sure that the access roles actually work and are applied correctly to every position.

[x] Relates to frontend
[x] Relates to the backend
[ ] Requires modification of GraphQL
[ ] Requires modification of Database
[ ] Requires creating a new service

**Comment by emilwihlander** [comment]
Found the reason, I am part of the DWWW-medlem group in keycloak, and eventhough that isn't an entry in the database, I will still have access!
