### ISSUE TITLE
Release-based deployment

### ISSUE THREAD

**Issue by oliverlevay** [Dsek-LTH/member-page#317]
## Short description of the feature
Build a 'stage' environment but only deploy to production on a new github release

[ x ] Depends on root ;)

**Comment by 01ste02** [comment]
Working on it - will deploy right after build and then deploy on member.sandbox.dsek.se, api.sandbox.dsek.se, minio.sandbox.dsek.se. Also, will only publish to production after either release has been made on github, or some other predetermined condition is fulfilled.

**Comment by oliverlevay** [comment]
Nice work! @01ste02
