### ISSUE TITLE
[booking] Implement a first booking graphql api

### ISSUE THREAD

**Issue by emilwihlander** [Dsek-LTH/member-page#36]
Implement a booking page for the members to book things. This is quite a large task.

Backend:
- Create a database table for storing booking information (e.g. 'bookings' with 'id', 'start_datetime', 'end_datetime','created_datetime','thing','member_id','event','status')
- Create a new service in the backend named 'bookings'
- Implement GraphQL endpoints for getting, updating, and creating the requests.
```graphql
bookingRequests(filter: BookingFilter): [BookingRequest]!

type BookingRequest {
  ...all fields
}

enum BookingStatus {
  WAITING
  ACCEPTED
  DENIED
}

input BookingFilter {
  from: Datetime
  to: Datetime
  status: BookingStatus
  ...
}

type BookingRequestMutations {
  accept(id: Int!): Boolean
  deny(id: Int!): Boolean
  remove(id: Int!): Boolean
  update(input: UpdateBookingRequest): Boolean
  create(input: CreateBookingRequest): Int
}

input UpdateBookingRequest {
  id: Int!
  start: Datetime
  end: Datetime
  thing: String
  event: String
}

input CreateBookingRequest {
  start: Datetime!
  end: Datetime!
  thing: String!
  event: String!
  member_id: Int!
}
```

Frontend:
- Create a UI for displaying the upcoming bookings, and their status (waiting, approved, denied)
- Create a UI for booking requests
- Create a UI for accepting/denying requests

The displaying should be available for everyone
The booking should be available for signed in members
The accepting/denying should be available for källarmästaren

**Comment by hnrklssn** [comment]
Backend work for this has been started in the Book'd repository and should be able to be migrated relatively easily
