### ISSUE TITLE
[calendar] Implement a first calendar graphql api

### ISSUE THREAD

**Issue by emilwihlander** [Dsek-LTH/member-page#37]
Implement a calendar api for viewing and creating upcoming events. Quite a large task.

Backend:
- Create a table for storing events (e.g. 'events' with 'id', 'start_datetime', 'end_datetime', 'title', 'description', 'link', ...)
- Create a new service called 'events'
- extend the GraphQL API to have actions for fetching and creating events.
```graphql
events(filter: EventFilter): [Event!]!

type Event {
  ...all fields
}

input EventFilter {
  id: Int
  from: Datetime
  to: Datetime
}

type EventMutations {
  create(input: CreateEvent): Int!
  update(input: UpdateEvent): Boolean!
  delete(id: Int!): Boolean!
}

input CreateEvent {
   ...
}

input UpdateEvent {
  ...
}
``` 

The displaying should be available for everyone
The creating should be available for signed in members
The updating/deleting should be available for the creator and a couple of select people (styrelsen + DWWW?)

**Comment by hnrklssn** [comment]
I think we should separate frontend and backend work into separate tasks when possible

**Comment by emilwihlander** [comment]
I agree, I will split this into 2 issues istead.
