### ISSUE TITLE
[sponsors] Add functionality for "Phaddergrupp" , add your own Phaddergrupp with a photo etc. 

### ISSUE THREAD

**Issue by oliverlevay** [Dsek-LTH/member-page#371]
[ x ] Relates to frontend
[ x ] Relates to the backend
[ ] Requires modification of GraphQL
[ ] Requires modification of Database
[ x ] Requires creating a new service

**Comment by fnurkla** [comment]
Phaddergrupp* ;)

Also, should you be able to create your own, or should nollningsutskottet do that?

**Comment by oliverlevay** [comment]
> Phaddergrupp* ;)
> 
> Also, should you be able to create your own, or should nollningsutskottet do that?

Yeah, that's a good point.

**Comment by oliverlevay** [comment]
We skip this one for now.
