### ISSUE TITLE
Implement a drawer

### ISSUE THREAD

**Issue by emilwihlander** [Dsek-LTH/member-page#41]
Implement the UI for a drawer, the options can be dummy names initially.

It should support categories.
should be open by default on desktop and cover the whole screen on mobile while open.

Depends on #28 (since it should match the new header aesthetically.

**Comment by LucasBoberg** [comment]
Är denna inte denna issue också fixad nu?

**Comment by emilwihlander** [comment]
Yes

**Comment by noahmay** [comment]
Closed by #105
