### ISSUE TITLE
Define group system for authorization

### ISSUE THREAD

**Issue by emilwihlander** [Dsek-LTH/member-page#45]
We need to define a group system that can be used for authorization.

I propose a hierarchic system to easily allow for access to large and small groups. For example, if you would be part of Källarmästeriet your access group would be `dsek.km` (I don't care what separator is used, could be whatever).

How to handle subgroups have 2 options:

- If you are part of a subgroup inside a committee you would ONLY have that group. For example, if you are part of DWWW your access group would be `dsek.km.dwww` and you wouldn't be part of `dsek.km`. This to minimize the number of groups you are part of.
- You have all the access groups so if you are part of dwww you would have `dsek`, `dsek.km`, and `dsek.km.dwww`.

For every level, `.head` and `.vice` would be reserved for the head och vice head of every group (both committees and subgroups).

This would mean that every committee will need a short name.

Thoughts?

**Comment by emilwihlander** [comment]
@nilsceberg @hnrklssn you may have valuable opinions and/or ideas regarding this?

**Comment by hnrklssn** [comment]
Given that subgroups would reasonably inherit the access levels of the parent group, the end result should be the same wrt what the use can access. So instead of having the person be part of many groups you could have each role be part of a group (potentially modelled as a group itself, but that may just be unnecessary abstraction for no benefit), and inherit all of that group's access and so on.

**Comment by emilwihlander** [comment]
Hardcoding head and vice might not be perfect, the reason would I purposed it was that it would be easy during access granting to know how to grant access to the head and vice head of a committee/group since all groups have at least a 'head of'.

The argument for giving all group levels to a member is if we're using a service (such as the root wiki) that might not support parsing (e.i. splitting the group) different levels it would be hard to give access to everyone in källarmästeriet, for example. It might feel redundant but I would have 12 access groups with and 8 access groups without, not that big of a difference.

Worth noting is that I think that the core/member service should define with access groups a user is included in but that it should be exported to keycloak for any service to use. There is a REST API available so this can be automated.

**Comment by emilwihlander** [comment]
I've (together with @hnrklssn @nilsceberg) have noticed that keycloak has two concepts, groups and roles. Each group has roles assigned to them. Therefore there should be a group per position (sv. post) and each group should have every applicable role. E.g. there would be a group named 'stabsmedlem' that would have the roles ['dsek', 'dsek.nollu', 'dsek.nollu.staben'].

The roles a user has are available in the jwt field realm_access.

These are the roles I think should be added:
```
dsek
dsek.aktu
dsek.cafe
dsek.infu
dsek.infu.dwww
dsek.km
dsek.km.root
dsek.naru
dsek.naru.alumni
dsek.nollu
dsek.nollu.staben
dsek.nollu.peppare
dsek.sex
dsek.sex.pub
dsek.sex.bar
dsek.sex.kok
dsek.sex.hov
dsek.skatt
dsek.srd
dsek.valb
dsek.medalj
dsek.fram
dsek.juble
```

**Comment by emilwihlander** [comment]
This is implemented in FreeIPA!
