### ISSUE TITLE
[frontend] Make switching languages take 1 click

### ISSUE THREAD

**Issue by fnurkla** [Dsek-LTH/member-page#460]
## Short description of the feature
At the moment it takes 2 clicks to switch language, for no good reason. 

[x] Relates to frontend
[ ] Relates to the backend
[ ] Requires modification of GraphQL
[ ] Requires modification of Database
[ ] Requires creating a new service

## Long description with technical specifications
At the moment when you click the language button it opens the following menu:
![language_switch](https://user-images.githubusercontent.com/97372888/194942932-1db1b191-0488-4c51-acd6-a823ca443e85.png)
This isn't necessary since there are only two different languages we use. It would be a better user experience to simply switch directly to the other language instead of having to pick the only available option.

**Comment by oliverlevay** [comment]
We might want to add more languages in the future and since #462 is fixed this shouldn't be an issue.
