### ISSUE TITLE
[frontend] Save language preference for user

### ISSUE THREAD

**Issue by AntiSC2** [Dsek-LTH/member-page#462]
My browser is set to English so the language on the site always default to English, even if I have switched to using Swedish before. It would be nice if I could save my language preference so when I'm logged in I will always be using my preferred language.

[x] Relates to frontend
[ ] Relates to the backend
[ ] Requires modification of GraphQL
[x] Requires modification of Database
[ ] Requires creating a new service

**Comment by oliverlevay** [comment]
This is fixed and building.
