### ISSUE TITLE
Fixa så att utskottsobjekten tar upp hela bredden på mobilen endast

### ISSUE THREAD

**Issue by oliverlevay** [Dsek-LTH/member-page#485]
På desktop har dessa en maxbredd, den skulle behöva tas bort på mobilen men vara kvar på desktopbredd.
![image](https://user-images.githubusercontent.com/22683219/195894060-2501f84d-5c3c-4da5-9e9a-25498a6eabe5.png)

**Comment by ludviggierup** [comment]
+ fixa så att cursor: pointer är på varje knapp och inte på hela diven

**Comment by oliverlevay** [comment]
Tip: use this
![image](https://user-images.githubusercontent.com/22683219/199538307-b2eb833f-a003-4a63-a84c-35f5c3c48be6.png)
