### ISSUE TITLE
👔  För över alla möteshandlingar

### ISSUE THREAD

**Issue by oliverlevay** [Dsek-LTH/member-page#486]
Just nu saknas möteshandlingar från 2018 och tidigare på hemsidan, dessa behövs föra över.

**Comment by oliverlevay** [comment]
I have now transferred to S08 2014

**Comment by BardNilz** [comment]
I think everything should be transferred now. Feel free to double-check @oliverlevay .

**Comment by oliverlevay** [comment]
Perfect 🙏 thank you for your hard work
