### ISSUE TITLE
För över alla SRD protokoll

### ISSUE THREAD

**Issue by oliverlevay** [Dsek-LTH/member-page#488]
Protokoll från
https://www.dsek.se/sektionen/srd/protokoll/
behöver föras över till 
https://member.dsek.se/documents/srd

**Comment by BardNilz** [comment]
Samtliga protokoll förutom följande 2002-04-24 samt alla från 1999 minus 1999-12-01 är nu överförda.

**Comment by oliverlevay** [comment]
Är alla överförda nu? @BardNilz I så fall kan du stänga denna issue : )

**Comment by BardNilz** [comment]
Samtliga överförda nu. De som inte fanns i PDF format blev överförda i HTML.
