### ISSUE TITLE
🎨 Designa en landningssida

### ISSUE THREAD

**Issue by oliverlevay** [Dsek-LTH/member-page#489]
https://esek.se/
E-sektionens nya sida är jättefin. Om new.dsek.se ocskå hade kunnat bli lika fin hade det varit fett. Ta inspiration av vilka funktioner som finns på denna sida, lägg till lite d-sek charm. Gör det till en figma.

**Comment by oliverlevay** [comment]
Vi behöver att denna sidan är klar ASAP

**Comment by 01ste02** [comment]
Har vi inte redan en sådan på new.dsek.se?

**Comment by oliverlevay** [comment]
> Har vi inte redan en sådan på new.dsek.se?

Jo det finns en, men jag ser den som en placeholder. Det kan inte vara vår officiella sida.

Dels vill vi ha en snyggare sida, och dels vill vi ha mer funktionalitet. Typ som att ha mer information, visa vår styrelse och andra saker som vi kan hämta från medlemsapiet. 

Jämför liksom https://new.dsek.se/ med https://esek.se/ , det är ju inte ens nära.

**Comment by oliverlevay** [comment]
Däremot kan vi ha det tills vidare, och jobba på new.dsek.se nästa år

**Comment by oliverlevay** [comment]
Slå ihop detta med huvudsidan
