### ISSUE TITLE
Roadmap: First deployment 

### ISSUE THREAD

**Issue by emilwihlander** [Dsek-LTH/member-page#51]
This issue includes what needs to be done before the first deployment to the servers. If more things are needed, they will be added.

- [ ] #31 
- [ ] #41 
- [ ] #45 
- [ ] #52

**Comment by hnrklssn** [comment]
Tänkte att du kanske inte kände till funktionaliteten, så jag skapade en milestone med samma innehåll: https://github.com/Dsek-LTH/member-page/milestone/1

**Comment by emilwihlander** [comment]
Milestones är nog en bättre lösning! Såg bara att andra repon hade löst motsvarande problematik med pinnade issues :)
