### ISSUE TITLE
Add the commit hash to the footer of the page

### ISSUE THREAD

**Issue by fnurkla** [Dsek-LTH/member-page#527]
At the moment, it's kinda difficult to know when your changes have reached production. For instance, I wasn't sure that the changes I made in #495 had made it and just weren't working for some reason or wasn't there yet.

My proposal is to add the (perhaps truncated) hash of the commit to the footer of the page. It shouldn't be intrusive, just a div with "commit ${hash}" in it.

**Comment by oliverlevay** [comment]
Great suggestion! It's implemented now.
