### ISSUE TITLE
[calendar] Implement UI

### ISSUE THREAD

**Issue by emilwihlander** [Dsek-LTH/member-page#59]
## Short description of the feature
Implement a first version of the UI for the calendar

Depends on #37

[x] Relates to frontend
[x] Relates to the backend
[ ] Requires modification of GraphQL
[ ] Requires modification of Database
[ ] Requires creating a new service

## Long description with technical specifications

- [x] Create a UI for displaying upcoming events, like a calendar.
- [x] Add filter on booking/event
- [x] Create a page per event, /event/[id]
- [x] Create a UI for creating an event
- [x] Create a UI for updating an Event
- [x] Implement remove functionality
- [x] Create list of events
- [x] #223

The displaying should be available for everyone
The creating should be available for signed in members
The updating/deleting should be available for the creator and a couple of select people (styrelsen + DWWW?)

**Comment by oliverlevay** [comment]
It works now but author gives an error on attempt to query it
