### ISSUE TITLE
Add automatic build of docker containers

### ISSUE THREAD

**Issue by emilwihlander** [Dsek-LTH/member-page#60]
## Short description of the feature
Make a github action build the prod containers with docker-compose on push and pull request to master.

[ ] Relates to frontend
[x] Relates to the backend
[ ] Requires modification of GraphQL
[ ] Requires modification of Database
[ ] Requires creating a new service

## Long description with technical specifications
Here are some resources that might be relevant:
https://medium.com/@onufrienkos/github-actions-with-docker-compose-node-js-and-mongodb-d59bf7e20867
https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-docker-container-action

**Comment by hnrklssn** [comment]
Jag har tillgång till dwwws konton på docker-hub och npm btw. Man kan knyta ihop docker-hub med GitHub så att den börjar bygga nästa version på varje versionstaggad commit, merge till master osv, och sen kan folk hämta docker images därifrån istället för att behöva bygga allt själva när de bara vill ändra i en av dem. :)

**Comment by emilwihlander** [comment]
This is done through the guilds jenkins server, therefore this is done ✅
