### ISSUE TITLE
✨ Add short_description field to articles

### ISSUE THREAD

**Issue by oliverlevay** [Dsek-LTH/member-page#631]
Just using the article body in notifications does not look good. 

![image](https://user-images.githubusercontent.com/22683219/201483481-2013a813-6ae3-4743-ac15-922ad6e893a0.png)

Long articles take up too much space.

**Comment by Macludde** [comment]
As discussed in person:

Should we instead add a field called "notification_body" which is a mandatory field for all news who choose to send a notification in which the author can specify the body of the notification (without markdown), with the same restrictions as the ones for notifications.

The alternative is to add a general "short_description" as the issue suggest, and use it both for notifications and for truncated articles. I do not like this as it gives rise to the same issues with markdown looking bad in notifications, ie not solving the issue at hand.
