### ISSUE TITLE
🎨 Make articles take up less space

### ISSUE THREAD

**Issue by oliverlevay** [Dsek-LTH/member-page#637]
Depends on #631 

On the home page and on the `/news` page the articles should be really smol, and then you can click on them to interact? I don't really know how this should be designed. All I know is that articles shouldn't be expanded by default on `/news`.

- [x] Make articles not expanded by default on `/news
- [ ] Use short_description instead of cutting the body.

**Comment by Macludde** [comment]
I fix

**Comment by Macludde** [comment]
I also think this is mostly and issue on the home page. Perhaps they can be larger on the /news page

**Comment by oliverlevay** [comment]
Don't forget to do #631 and use short_description

Then we can have something like this

![image](https://user-images.githubusercontent.com/22683219/201690358-4e30d53e-1e32-4630-8c92-5e4b7cd022c6.png)
