### ISSUE TITLE
💄 Make tag colors theme specific

### ISSUE THREAD

**Issue by fnurkla** [Dsek-LTH/member-page#721]
Right now, some tag colors stand out well on one theme background, but not on the other.

For example, the "Nominations" tag is very visible on a light background:
![nomineringar_light](https://user-images.githubusercontent.com/97372888/203445301-0a638cb2-ee58-4fad-a51c-54303ebafe81.png)
But not so visible on a dark background:
![nomineringar_dark](https://user-images.githubusercontent.com/97372888/203445302-7a1be5d2-9d0e-4766-9399-efc51d44230e.png)

I propose making the tag color dependent on the mode so that it always stands out well against the background.

**Comment by oliverlevay** [comment]
What do you think @Macludde ?

**Comment by DannyTang002** [comment]
I agree, right now it can be a bit hard to see. For example having the tag in white would make it more visible.

![98116d884f5b0baf5db8bf258f81f278](https://user-images.githubusercontent.com/90634685/203620440-a36218dd-9fa5-4541-a01d-f78db0a91d6e.png)

**Comment by HienMyTruong** [comment]
Having the darkmode tag in a lighter blue and vice versa would certainly help.

**Comment by BardNilz** [comment]
Agreed. There should be a contrast between the colors of the tags and the background color. Preferably, changing as the user swap between dark/light mode.

**Comment by oliverlevay** [comment]
I interpret this as this is a feature we want.

**Comment by Macludde** [comment]
I agree.
