### ISSUE TITLE
✨ Build a system for elections

### ISSUE THREAD

**Issue by oliverlevay** [Dsek-LTH/member-page#725]
1. Collect a set of  mecenat_id and make sure that they are valid and belongs to our guild, this can be done through google forms.
2. Hash and salt the mecenat_id before adding it to the `voter_register` table
3. When the user tries to vote, they enter their mecenat_id and which is hashed & salted and compared with the existing mecenat_id in the database.

**Comment by AntiSC2** [comment]
I don't think we should build our own election system. Systems already exists for this and other guilds have their own voting systems open-source. We could use theirs and save a lot of hours compared to building our own.

**Comment by fnurkla** [comment]
I know that root has looked into using [voteit](https://www.voteit.se/) as well. The issue there being that it's pretty complicated to set up as it stands right now.

**Comment by oliverlevay** [comment]
@danieladugyan maybe we should close this issue? @01ste02 and root has a solution coming up right?

**Comment by 01ste02** [comment]
*rootm - I am root :)

We have voteit in the works, so yes. You can probably close this.
