### ISSUE TITLE
🐛 Change favicon to dsek pink

### ISSUE THREAD

**Issue by HienMyTruong** [Dsek-LTH/member-page#734]
<img width="278" alt="Screenshot 2022-11-24 at 18 49 05" src="https://user-images.githubusercontent.com/89738337/203843217-35701ef0-fded-4f5b-a4d1-b55fb6fa0c6f.png">

Favicon not visable on dark mode

**Comment by oliverlevay** [comment]
https://youtube.com/shorts/o5WNKVkm1HA?feature=share

Apparently favicon can be customized to match
