### ISSUE TITLE
✨ Infinite scroll

### ISSUE THREAD

**Issue by Macludde** [Dsek-LTH/member-page#776]
Replace pagination on news page with infinite scroll.
## Short description of the feature
When you start to reach the end, fetch X more news.

This could be done by changing the query to either use LIMIT and OFFSET (and caching in frontend), or just fetch X latest post (where X is increased as the user scrolls). I would try both and check the network use as well as performance, we might need to stop rerendering posts at the start of the feed when the user scrolls far enough.

**Comment by oliverlevay** [comment]
We prefer having pagination.
