### ISSUE TITLE
Set up linting

### ISSUE THREAD

**Issue by frednordell** [Dsek-LTH/member-page#8]
We only need to decide on a style for the different files, i like google's styles but are open to suggestions

**Comment by oliverlevay** [comment]
Google sounds good. I can set it up if its ok :)

**Comment by frednordell** [comment]
Go right ahead! 👍

**Comment by oliverlevay** [comment]
Hm.... At a second thought how would linting work in this monorepo? Would I install it in all the different workspaces or just in "frontend" or how would that work?

**Comment by LucasBoberg** [comment]
Check this out might be useful https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/MONOREPO.md

**Comment by LucasBoberg** [comment]
Then I guess we can discuss it on saturday
