### ISSUE TITLE
Investigate documentation implementation

### ISSUE THREAD

**Issue by noahmay** [Dsek-LTH/member-page#80]
## Short description of the feature
How should we document the functionality?

[x] Relates to frontend
[ ] Relates to the backend
[ ] Requires modification of GraphQL
[ ] Requires modification of Database
[x] Requires creating a new service

**Comment by noahmay** [comment]
Maybe this? https://docusaurus.io/

**Comment by LucasBoberg** [comment]
We could just use github wiki
