### ISSUE TITLE
✨ Implements photos service

### ISSUE THREAD

**Issue by noahmay** [Dsek-LTH/member-page#81]
## Short description of the feature
A first implementation of a photo archive.

[x] Relates to frontend
[x] Relates to the backend
[x] Requires modification of GraphQL
[x] Requires modification of Database
[x] Requires creating a new service

**Comment by noahmay** [comment]
it might be better to use a open-source solution instead of creating our own. [PhotoPrism ](https://photoprism.app/)looks promising.

They are currently working on OpenId connect authentication which would be required for us to use it. See this issue: https://github.com/photoprism/photoprism/issues/782

**Comment by noahmay** [comment]
it might be better to use an open-source solution instead of creating our own. [PhotoPrism ](https://photoprism.app/)looks promising.

They are currently working on OpenId connect authentication which would be required for us to use it.

**Comment by oliverlevay** [comment]
Make a rudamentary photo service
