### ISSUE TITLE
🐛 Front page: news and event cards are not fixed width

### ISSUE THREAD

**Issue by sadphi** [Dsek-LTH/member-page#824]
## Short description of the bug
On dekstop, the cards under "Senaste nyheterna" and "Kommande evenemang" are not fixed width, which makes the page less visually appealing.

## To Reproduce
On a desktop/laptop, enter [https://member.dsek.se](https://member.dsek.se) and scroll down. However, it's not always visible since it depends on the content.

## Expected behavior
The cards should be fixed width.

## Actual behavior
The cards vary in width depending on their contents.

## Context
Note that I've removed some personal information in the screenshot.
![issue](https://user-images.githubusercontent.com/24957263/207597503-2fed236f-49ac-4d34-bd4c-b87c5650ef3d.jpg)

## Environment
 - **Device**: Desktop
 - **OS**: Windows 10
 - **Browser**: Firefox
 - **Version**: 108.0

**Comment by oliverlevay** [comment]
Thank you! Hopefully this is fixed now, let me know if the issue persists.
