### ISSUE TITLE
Investigate page for about info 

### ISSUE THREAD

**Issue by noahmay** [Dsek-LTH/member-page#83]
A page where general info can be accessed (e.g. graphic profile, organization structure)

[x] Relates to frontend
[ ] Relates to the backend
[ ] Requires modification of GraphQL
[ ] Requires modification of Database
[ ] Requires creating a new service

**Comment by oliverlevay** [comment]
https://member.dsek.se/committees/030a261c-b6d4-40a0-84cc-bca7249d7ffb
"Här kommer det att finnas text som utskotten själva kan ändra på!" , maybe add an editor?
