### ISSUE TITLE
🐛 Fix mobile view on some pages

### ISSUE THREAD

**Issue by Macludde** [Dsek-LTH/member-page#854]
The following pages have issues:

News:
- Keyboard is automatically shown when clicking on tags dropdown, perhaps just open dropdown on first click and open keyboard on second.

News -> Tags:
- The page does not look good on mobile, in its entirety

Documents -> Meeting Documents:
- Year filter is too wide (does not wrap)

Booking -> Bookables:
- Like tags view it is not adapted for mobile

**Comment by oliverlevay** [comment]
Split these to different issues please @Macludde

**Comment by Macludde** [comment]
Split into different issues. See #969, #970 and #971
