### ISSUE TITLE
✨ Add option to see history of bookings

### ISSUE THREAD

**Issue by julialovisakarlsson** [Dsek-LTH/member-page#860]
## Short description of the feature
It should be possible to see who has made bookings before, maybe only for Head of Facilities since they are responsible for the locals and inventory. They also oversee the bookings in the first place. It would be good to save *at least* the last 5 bookings for every bookable item. 

## Why do you want this feature?
If something is wrong after a booking it would be good to know who last had/used it. Having at least the last 5 bookings is for in case a frequently used item breaks, and there have been a couple bookings since it could be used properly. I want to be able to keep track of who to talk to about what happened, in case no one tells me directly that something broke.  

## Who else could want this feature?
... Future Head of Facilities? :)

**Comment by danieladugyan** [comment]
Additionally, bookings that recently expired (past 24h?) shouldn't be listed under active bookings.
