### ISSUE TITLE
🐛 Booking page table header covers profile popup

### ISSUE THREAD

**Issue by julialovisakarlsson** [Dsek-LTH/member-page#861]
## Short description of the bug
The popup that shows up when pressing your own profile picture is behind the header row of the booking table. It works correctly for notifications. 

## To Reproduce
Go to booking page. Press profile picture so "log out" button is visible. Scroll down.

## Expected behavior
Popup should be in front of everything

## Actual behavior
It's not

## Context
Video showing it:

https://user-images.githubusercontent.com/71255627/213893414-07f2ad86-e4ef-4b9e-a4fe-31da05ba3136.mov

**Comment by julialovisakarlsson** [comment]
Add on: booking table header row is in front of the entire menu (Hem, nyheter, evenemang...) too.

**Comment by Macludde** [comment]
Fixed in #1010
