### ISSUE TITLE
🐛 The policy documents are not up to date

### ISSUE THREAD

**Issue by sofiatatidis** [Dsek-LTH/member-page#897]
## Short description of the bug
Not all policy documents are up to date. (The ones that are up to date is mostly due to them not being updated recently.) My guess is that the policies were just moved from the old website (where they were also not up to date) to the new. However, the most recent version, and as such the accurate version, of the policies can be found on our github page. Perhaps there's a way to automatically update the policies on the website once changes have been made to the repo? 

## To Reproduce
For example, open "Policy för fonder".

## Expected behavior
The most recent change was made in 2022 (as specified by the github repo where the actual versions of all policies are located).

## Actual behavior
The most recent change, as noted in the version on the website, was in 2021.

## Context
[Link to the repo of all policies](https://github.com/Dsek-LTH/policys)

**Comment by fnurkla** [comment]
Perhaps another option is to make the CI job for the policies update the documents on the website somehow?
