### ISSUE TITLE
✨ Remove nicknames when user is not logged in

### ISSUE THREAD

**Issue by AndreasAnderberg** [Dsek-LTH/member-page#914]
## Short description of the feature
Do not show the nicknames of people who have posted news articles unless the reader has logged in. For example: if you're viewing an article posted by "Andreas 'Anreas' Anderberg" while not logged in, the name of the person posting the article should be only "Andreas Anderberg".

## Why do you want this feature?
Many non-members has visited our website or will do so in soon. For example many companies who come in contact with the guild for the first time do a quick google search to find out more about us and end up on the website. While nicknames are fun, they can also be crude, vulgar or simply unserious and can ruin the first impression of the website and, by extension, the guild. 
By removing them only when not logged in they are only seen by members (who are logged in) and the problem is solved. 

## Who else could want this feature?
Guild members who want to keep their fun nicknames without making a bad impression on a potential future employer.

**Comment by Macludde** [comment]
Question: Should a user's nickname be hidden across the entirety of the site, or perhaps visible on pages such as the user's account page?
