### ISSUE TITLE
✨Notify Head of Facilities on changed booking request

### ISSUE THREAD

**Issue by danieladugyan** [Dsek-LTH/member-page#924]
Currently, the Head of Facilities (Källarmästaren) gets a notification whenever someone creates a new booking request over at https://www.dsek.se/booking. But they don't get a notification when someone cancels their booking, or when someone changes their booking.

### To-do
- [x] Send a notification on booking cancellation
- [ ] Include info in notification message (datettime and "item")

**Comment by klaratjernstrom** [comment]
The notification message becomes quite long when all information is included in message. Could it be more approriate to only include event name? Example: "Klara Tjernström has updated a booking request: InfUkväll"
