### ISSUE TITLE
⚡ Webshop administration

### ISSUE THREAD

**Issue by danieladugyan** [Dsek-LTH/member-page#925]
Users with the correct permissions must be able to:
- [x] Create events
- [x] View purchasers of a given event

**Comment by auoldenburg** [comment]
This is a suggestion for how to structure this feature for lunch lectures:

Admin clicks on Admin -> Webshop
Sidebar has 2 tabs: 

- **Create event**
- **Manage event**
	
**Create event:**
_(Enhancement: admin is met with option of choosing between some pre-made options (lunch lectures, sittning etc.) where some information is already filled in automatically, like having a question asking for food preferences for lunch lectures)_

**Admin has to input the following information:**
- Title
- Price (free for lunch lectures)
- Time of event
- Location
- What time to publish the event to the public
- What time users can start booking tickets to said event
- What time the selling of tickets closes on
- Amount of free slots
- Product description (with english version being mandatory?)
- Mail/contact information to responsible host
- Link to purchase conditions (links to separate page)

**Admin is free to add this additional information:**
- Event picture
- Question(s) with written user responses
  - Admin has the option to make a selection of these mandatory
- Question(s) presenting alternatives for users
  - Admin has the option to make a selection of these mandatory

**Button at the bottom confirms creation of event**
_(Enhancement: notification is sent out when event is published, is open to book tickets for, closes within a given timeframe (time can be set by admin on creation?))_

**Manage event:**
Admin is presented with some information of said event:
- Number of sold tickets
- Number of tickets left
- List of users that have bought tickets and their answers to question
  - This information can be downloaded as .csv
	
**Admin can edit the following:**
- If event is not "live", i.e. tickets have not yet been released:
  - Everything in "create event" tab
- If event is "live", i.e. tickets can be bought
  - Event picture
  - Title
  - Time of event
  - Amount of free slots (only increase from previous cap)
  - Product description
  - Time to close ticket sales

See linked issues below for some parts of above implementation plan.

**Comment by danieladugyan** [comment]
@Macludde Please split this up into separate issues:
* Product creation (called "Create event" above)
* Product forms (listed under "Admin is free to add this additional information" above)
* Manage product (called "Manage event" above)
* Product editing (listed under "Admin can edit the following" above)
* OPTIONALLY: Notifications for product changes

Additionally, maybe event is a confusing name considering we already have something called events. I'd just treat everything as products.
