### ISSUE TITLE
[news] Look into slugs

### ISSUE THREAD

**Issue by LucasBoberg** [Dsek-LTH/member-page#94]
## Short description of the feature
Look into slugs for news for nicer looking urls

[x] Relates to frontend
[x] Relates to the backend
[x] Requires modification of GraphQL
[x] Requires modification of Database
[ ] Requires creating a new service

**Comment by oliverlevay** [comment]
the url should probably be `[id]/slug`, look also into this feature in events

**Comment by oliverlevay** [comment]
shorten the uuid so it looks nicer, base64 version of uuid
