### ISSUE TITLE
🐛 Long file names without spaces does not wrap

### ISSUE THREAD

**Issue by sofiatatidis** [Dsek-LTH/member-page#947]
So you encountered a bug?  😝 🐛 We really appreciate your help! 🥇 
## Short description of the bug
Long file names that does not contain any spaces are not wrapped. This looks odd on smaller screens.

## To Reproduce
Check out the meeting document for S07 2023 on a mobile device.

## Expected behavior
The text should wrap and behave just as when the long title contains spaces.

## Actual behavior
No wrap of the text. The text overflows.

## Context
![Screenshot_20230224_112231](https://user-images.githubusercontent.com/71378384/221154668-ab9cf964-d09b-4a33-b97f-97905b24dd5b.png)

## Environment (If applicable)
On smaller screen, mostly phone screens.

**Comment by Macludde** [comment]
This has been fixed in #965
