### ISSUE TITLE
🐛 Email links for 'dwww@dsek.se' and 'webmaster@dsek.se' not triggering 'mailto:' function on 'Informationsutskottet' page

### ISSUE THREAD

**Issue by BardNilz** [Dsek-LTH/member-page#975]
## Short description of the bug
At "Sektionen" -> "Utskott" -> "Informationsutskottet" several different emails are shown. Most of which works as expected with a "mailto:" function. However, "dwww@dsek.se" and "webmaster@dsek.se" does not.  If one of the two aforementioned email addresses is clicked, you get sent to the following page.

![image](https://user-images.githubusercontent.com/80070896/226677475-0d9ca918-b67f-4be4-96b6-c0bff361e6be.png)

## Expected behavior
Make all of the addresses work with the "mailto:" function.

**Comment by Macludde** [comment]
This is a simple markdown fix, @oliverlevay I think you have access to change markdown on the InfU page.
